title = "Houze ZHANG"
languageCode = "en-us"
theme = 'smol'

toc = true

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Houze ZHANG 张厚泽"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/in/houzezhang"

[params]
    subtitle = "Software Engineer at Google"
    dateFmt = "02.01.2006 15:04"

[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 

  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

  [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 4

  [[menu.footer]]
        name = "Linkedin"
        url = "https://www.linkedin.com/in/houzezhang"
        weight = 1
